apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: asm-adapter # example: bookinfo-service-mesh-adapter
  namespace: mythical-retail # example: default
  labels:
    service-mesh.mulesoft.com/kind: adapter
spec:
  clusterServiceClassExternalName: anypoint-service-mesh-adapter
  clusterServicePlanExternalName: small # example: small.
  parameters:
    platformUri: https://anypoint.mulesoft.com # example: https://eu1.anypoint.mulesoft.com
    replication:
      replicas: 2 # example: 2
  parametersFrom: # The element specifies the secret name and configuration required for retrieving the parameters
    - secretKeyRef:
        name: asm-adapter-config # example: bookinfo-service-mesh-adapter-config
        key: config